import {
  User,
  CollectionRequest,
  WasteRecord,
  MobileUnit,
  VirtualContainer,
  Alert,
  ActivityLog,
  SystemSettings,
} from './types';

export const HOSPITAL_DEPARTMENTS = [
  'Emergency',
  'ICU',
  'Laboratory',
  'Pharmacy',
  'Ward A',
  'Ward B',
  'Operation Theatre',
  'Outpatient Department',
  'General Medicine',
  'Storage',
];

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-01',
    name: 'Dr. Evelyn Vance',
    email: 'evelyn.vance@hospital.org',
    role: 'ADMIN',
    department: 'Hospital Administration',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'ADM-8901',
    lastActive: 'Just now',
  },
  {
    id: 'USR-02',
    name: 'Marcus Brody',
    email: 'marcus.brody@hospital.org',
    role: 'WASTE_MANAGER',
    department: 'Environmental Services & Safety',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'WM-3420',
    lastActive: '3 mins ago',
  },
  {
    id: 'USR-03',
    name: 'Nurse Priya Sharma',
    email: 'priya.sharma@hospital.org',
    role: 'STAFF',
    department: 'Emergency',
    avatar: 'https://images.unsplash.com/photo-1594824813689-d3e91d5ebc98?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'STF-1102',
    lastActive: '12 mins ago',
  },
  {
    id: 'USR-04',
    name: 'Dr. James Thorne',
    email: 'james.thorne@hospital.org',
    role: 'WASTE_MANAGER',
    department: 'Infection Control Unit',
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'WM-4491',
    lastActive: '25 mins ago',
  },
  {
    id: 'USR-05',
    name: 'Carlos Mendez, RN',
    email: 'carlos.mendez@hospital.org',
    role: 'STAFF',
    department: 'ICU',
    avatar: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'STF-5582',
    lastActive: '1 hour ago',
  },
  {
    id: 'USR-06',
    name: 'Sarah Lindqvist',
    email: 'sarah.lindqvist@hospital.org',
    role: 'STAFF',
    department: 'Laboratory',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'STF-9931',
    lastActive: '45 mins ago',
  },
  {
    id: 'USR-07',
    name: 'Hassan Al-Mansoor',
    email: 'hassan.mansoor@hospital.org',
    role: 'STAFF',
    department: 'Operation Theatre',
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'STF-6623',
    lastActive: '2 hours ago',
  },
  {
    id: 'USR-08',
    name: 'Elena Rostova',
    email: 'elena.rostova@hospital.org',
    role: 'STAFF',
    department: 'Pharmacy',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'STF-4412',
    lastActive: '15 mins ago',
  },
  {
    id: 'USR-09',
    name: 'David Kalu',
    email: 'david.kalu@hospital.org',
    role: 'STAFF',
    department: 'Ward A',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'STF-8819',
    lastActive: '3 hours ago',
  },
  {
    id: 'USR-10',
    name: 'Mei-Ling Chen',
    email: 'meiling.chen@hospital.org',
    role: 'ADMIN',
    department: 'Bio-Safety & Regulatory',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    badgeNumber: 'ADM-7104',
    lastActive: '5 mins ago',
  },
];

export const INITIAL_CONTAINERS: VirtualContainer[] = [
  {
    id: 'CONTAINER_A',
    name: 'CONTAINER A',
    label: 'General Waste',
    category: 'GENERAL',
    color: 'emerald',
    capacityKg: 100,
    currentWeightKg: 42.5,
    capacityPercent: 43,
    itemCount: 38,
    status: 'NORMAL',
    lastUpdated: '10:45 AM',
    description: 'Uncontaminated packaging, office paper, clean paper towels, non-clinical items.',
  },
  {
    id: 'CONTAINER_B',
    name: 'CONTAINER B',
    label: 'Infectious Soft Waste',
    category: 'INFECTIOUS_SOFT',
    color: 'amber',
    capacityKg: 80,
    currentWeightKg: 54.8,
    capacityPercent: 68,
    itemCount: 64,
    status: 'FILLING',
    lastUpdated: '10:48 AM',
    description: 'Blood-stained dressings, soiled swabs, cotton, gloves, PPE, microbiological cultures.',
  },
  {
    id: 'CONTAINER_C',
    name: 'CONTAINER C',
    label: 'Sharps Waste',
    category: 'SHARPS',
    color: 'rose',
    capacityKg: 40,
    currentWeightKg: 36.4,
    capacityPercent: 91, // NEAR FULL -> Alert!
    itemCount: 72,
    status: 'NEAR FULL',
    lastUpdated: '10:50 AM',
    description: 'Rigid puncture-resistant bin for hypodermic needles, scalpels, trocars, broken glass.',
  },
  {
    id: 'CONTAINER_D',
    name: 'CONTAINER D',
    label: 'Pharmaceutical Waste',
    category: 'PHARMACEUTICAL',
    color: 'violet',
    capacityKg: 50,
    currentWeightKg: 18.2,
    capacityPercent: 36,
    itemCount: 22,
    status: 'NORMAL',
    lastUpdated: '09:30 AM',
    description: 'Expired medication, chemotherapeutic residues, discarded vaccines and ampoules.',
  },
];

export const INITIAL_MOBILE_UNITS: MobileUnit[] = [
  {
    id: 'MEDI-01',
    name: 'MEDI-01 (Apex)',
    status: 'COLLECTING',
    assignedRequestId: 'CR-1024',
    currentDepartment: 'Emergency',
    batteryLevel: 88,
    collectionProgress: 75,
    currentTask: 'Collecting sharps disposal pack at Resuscitation Bay 2',
    lastActivity: '10:51 AM',
    speedMps: 0.8,
    coordinates: { x: 78, y: 72 },
    targetCoordinates: { x: 80, y: 75 },
  },
  {
    id: 'MEDI-02',
    name: 'MEDI-02 (Beacon)',
    status: 'COLLECTING',
    assignedRequestId: 'CR-1025',
    currentDepartment: 'Ward B',
    batteryLevel: 72,
    collectionProgress: 45,
    currentTask: 'Transit to Ward B soiled utility room',
    lastActivity: '10:49 AM',
    speedMps: 0.75,
    coordinates: { x: 32, y: 64 },
    targetCoordinates: { x: 30, y: 60 },
  },
  {
    id: 'MEDI-03',
    name: 'MEDI-03 (Cipher)',
    status: 'RETURNING',
    assignedRequestId: 'CR-1021',
    currentDepartment: 'Laboratory',
    batteryLevel: 28, // Low simulated battery -> warning alert
    collectionProgress: 95,
    currentTask: 'Returning biological samples canister to Central Segregation Vault',
    lastActivity: '10:47 AM',
    speedMps: 0.9,
    coordinates: { x: 48, y: 35 },
    targetCoordinates: { x: 50, y: 50 },
  },
  {
    id: 'MEDI-04',
    name: 'MEDI-04 (Delta)',
    status: 'AVAILABLE',
    currentDepartment: 'Storage',
    batteryLevel: 100,
    collectionProgress: 0,
    currentTask: 'Docked at Base Station 1 (Ready for dispatch)',
    lastActivity: '10:30 AM',
    speedMps: 0.0,
    coordinates: { x: 50, y: 50 },
    targetCoordinates: { x: 50, y: 50 },
  },
];

export const INITIAL_COLLECTION_REQUESTS: CollectionRequest[] = [
  {
    id: 'CR-1024',
    department: 'Emergency',
    category: 'SHARPS',
    estimatedQuantityKg: 4.5,
    priority: 'URGENT',
    requestedDate: '2026-09-11',
    requestedTime: '10:40 AM',
    notes: 'Post-trauma suture needles and scalpel disposals. Priority pickup needed.',
    status: 'COLLECTING',
    assignedUnitId: 'MEDI-01',
    requestedBy: 'Nurse Priya Sharma',
  },
  {
    id: 'CR-1025',
    department: 'Ward B',
    category: 'INFECTIOUS_SOFT',
    estimatedQuantityKg: 6.2,
    priority: 'HIGH',
    requestedDate: '2026-09-11',
    requestedTime: '10:35 AM',
    notes: 'Morning dressing rounds completed. Isolation room 204 biohazard bags.',
    status: 'COLLECTING',
    assignedUnitId: 'MEDI-02',
    requestedBy: 'David Kalu',
  },
  {
    id: 'CR-1026',
    department: 'Operation Theatre',
    category: 'INFECTIOUS_SOFT',
    estimatedQuantityKg: 9.0,
    priority: 'URGENT',
    requestedDate: '2026-09-11',
    requestedTime: '10:44 AM',
    notes: 'OT-3 cardiac surgery completed. Drape packs and surgical gauze.',
    status: 'ASSIGNED',
    assignedUnitId: 'MEDI-04',
    requestedBy: 'Hassan Al-Mansoor',
  },
  {
    id: 'CR-1027',
    department: 'Pharmacy',
    category: 'PHARMACEUTICAL',
    estimatedQuantityKg: 2.8,
    priority: 'MEDIUM',
    requestedDate: '2026-09-11',
    requestedTime: '10:15 AM',
    notes: 'Cytotoxic return vials and expired ampicillin ampoules.',
    status: 'PENDING',
    requestedBy: 'Elena Rostova',
  },
  {
    id: 'CR-1028',
    department: 'ICU',
    category: 'INFECTIOUS_SOFT',
    estimatedQuantityKg: 7.5,
    priority: 'HIGH',
    requestedDate: '2026-09-11',
    requestedTime: '10:20 AM',
    notes: 'Ventilator tubing and suction liners from Bed 4 & 7.',
    status: 'PENDING',
    requestedBy: 'Carlos Mendez, RN',
  },
  {
    id: 'CR-1029',
    department: 'Laboratory',
    category: 'GENERAL',
    estimatedQuantityKg: 5.0,
    priority: 'LOW',
    requestedDate: '2026-09-11',
    requestedTime: '09:50 AM',
    notes: 'Clean packaging boxes and reagent foam inserts.',
    status: 'PENDING',
    requestedBy: 'Sarah Lindqvist',
  },
  {
    id: 'CR-1030',
    department: 'Ward A',
    category: 'GENERAL',
    estimatedQuantityKg: 4.2,
    priority: 'LOW',
    requestedDate: '2026-09-11',
    requestedTime: '09:30 AM',
    notes: 'Patient food trays and clean paper wrappers from linen change.',
    status: 'PENDING',
    requestedBy: 'David Kalu',
  },
  {
    id: 'CR-1031',
    department: 'Emergency',
    category: 'SHARPS',
    estimatedQuantityKg: 3.1,
    priority: 'HIGH',
    requestedDate: '2026-09-11',
    requestedTime: '10:05 AM',
    notes: 'IV cannula stylets and blood collection lancets from triage.',
    status: 'PENDING',
    requestedBy: 'Nurse Priya Sharma',
  },
  {
    id: 'CR-1023',
    department: 'Outpatient Department',
    category: 'GENERAL',
    estimatedQuantityKg: 6.8,
    priority: 'LOW',
    requestedDate: '2026-09-11',
    requestedTime: '09:15 AM',
    notes: 'Sanitary bins and non-infectious consultation refuse.',
    status: 'COMPLETED',
    assignedUnitId: 'MEDI-03',
    requestedBy: 'Dr. James Thorne',
    completedAt: '10:12 AM',
  },
  {
    id: 'CR-1022',
    department: 'ICU',
    category: 'INFECTIOUS_SOFT',
    estimatedQuantityKg: 8.4,
    priority: 'URGENT',
    requestedDate: '2026-09-11',
    requestedTime: '08:45 AM',
    notes: 'Dialysis filter bags and bloody drain line waste.',
    status: 'COMPLETED',
    assignedUnitId: 'MEDI-01',
    requestedBy: 'Carlos Mendez, RN',
    completedAt: '09:30 AM',
  },
  {
    id: 'CR-1021',
    department: 'Laboratory',
    category: 'SHARPS',
    estimatedQuantityKg: 3.9,
    priority: 'HIGH',
    requestedDate: '2026-09-11',
    requestedTime: '08:30 AM',
    notes: 'Microscope slides, capillary tubes, and culture swabs.',
    status: 'COMPLETED',
    assignedUnitId: 'MEDI-02',
    requestedBy: 'Sarah Lindqvist',
    completedAt: '09:10 AM',
  },
  {
    id: 'CR-1020',
    department: 'General Medicine',
    category: 'GENERAL',
    estimatedQuantityKg: 11.2,
    priority: 'LOW',
    requestedDate: '2026-09-11',
    requestedTime: '08:00 AM',
    notes: 'Morning facility cleaning round waste bags.',
    status: 'COMPLETED',
    assignedUnitId: 'MEDI-04',
    requestedBy: 'Marcus Brody',
    completedAt: '08:52 AM',
  },
  {
    id: 'CR-1019',
    department: 'Pharmacy',
    category: 'PHARMACEUTICAL',
    estimatedQuantityKg: 4.1,
    priority: 'MEDIUM',
    requestedDate: '2026-09-11',
    requestedTime: '07:30 AM',
    notes: 'Batch verification discarded packaging & expired syrups.',
    status: 'COMPLETED',
    assignedUnitId: 'MEDI-03',
    requestedBy: 'Elena Rostova',
    completedAt: '08:20 AM',
  },
  {
    id: 'CR-1018',
    department: 'Emergency',
    category: 'INFECTIOUS_SOFT',
    estimatedQuantityKg: 5.5,
    priority: 'URGENT',
    requestedDate: '2026-09-11',
    requestedTime: '07:15 AM',
    notes: 'Night-shift acute stabilization waste.',
    status: 'COMPLETED',
    assignedUnitId: 'MEDI-01',
    requestedBy: 'Nurse Priya Sharma',
    completedAt: '07:55 AM',
  },
  {
    id: 'CR-1017',
    department: 'Operation Theatre',
    category: 'SHARPS',
    estimatedQuantityKg: 2.2,
    priority: 'HIGH',
    requestedDate: '2026-09-11',
    requestedTime: '06:40 AM',
    notes: 'Emergency orthopedic pin cutter fragments. [Cancelled: Disposed directly into wall-mounted safety vault.]',
    status: 'CANCELLED',
    requestedBy: 'Hassan Al-Mansoor',
  },
];

export const INITIAL_WASTE_RECORDS: WasteRecord[] = [
  {
    id: 'WR-2091',
    category: 'SHARPS',
    department: 'Emergency',
    weightKg: 3.8,
    classification: 'SHARPS',
    confidence: 0.96,
    containerId: 'CONTAINER_C',
    collectedBy: 'MEDI-01',
    date: '2026-09-11',
    time: '10:15 AM',
    status: 'VERIFIED',
    riskLevel: 'CRITICAL',
    explanation: 'Detected multiple puncture hazards and steel bevel tips.',
  },
  {
    id: 'WR-2090',
    category: 'INFECTIOUS_SOFT',
    department: 'Ward B',
    weightKg: 5.4,
    classification: 'INFECTIOUS_SOFT',
    confidence: 0.94,
    containerId: 'CONTAINER_B',
    collectedBy: 'MEDI-02',
    date: '2026-09-11',
    time: '09:55 AM',
    status: 'VERIFIED',
    riskLevel: 'HIGH',
    explanation: 'Soiled surgical pads with biological fluid saturation.',
  },
  {
    id: 'WR-2089',
    category: 'GENERAL',
    department: 'Outpatient Department',
    weightKg: 8.2,
    classification: 'GENERAL',
    confidence: 0.98,
    containerId: 'CONTAINER_A',
    collectedBy: 'MEDI-03',
    date: '2026-09-11',
    time: '09:40 AM',
    status: 'VERIFIED',
    riskLevel: 'LOW',
    explanation: 'Uncontaminated office stationery and clean packaging paper.',
  },
  {
    id: 'WR-2088',
    category: 'PHARMACEUTICAL',
    department: 'Pharmacy',
    weightKg: 2.3,
    classification: 'PHARMACEUTICAL',
    confidence: 0.91,
    containerId: 'CONTAINER_D',
    collectedBy: 'MEDI-03',
    date: '2026-09-11',
    time: '09:20 AM',
    status: 'VERIFIED',
    riskLevel: 'MEDIUM',
    explanation: 'Liquid antibiotic ampoules and blister packaging residue.',
  },
  {
    id: 'WR-2087',
    category: 'INFECTIOUS_SOFT',
    department: 'ICU',
    weightKg: 6.9,
    classification: 'INFECTIOUS_SOFT',
    confidence: 0.92,
    containerId: 'CONTAINER_B',
    collectedBy: 'MEDI-01',
    date: '2026-09-11',
    time: '08:50 AM',
    status: 'VERIFIED',
    riskLevel: 'HIGH',
    explanation: 'Single-use respiratory circuits and secretion swabs.',
  },
  {
    id: 'WR-2086',
    category: 'SHARPS',
    department: 'Laboratory',
    weightKg: 2.7,
    classification: 'SHARPS',
    confidence: 0.95,
    containerId: 'CONTAINER_C',
    collectedBy: 'MEDI-02',
    date: '2026-09-11',
    time: '08:35 AM',
    status: 'VERIFIED',
    riskLevel: 'CRITICAL',
    explanation: 'Centrifuge hematocrit tubes and broken pipette ends.',
  },
  {
    id: 'WR-2085',
    category: 'GENERAL',
    department: 'General Medicine',
    weightKg: 11.2,
    classification: 'GENERAL',
    confidence: 0.99,
    containerId: 'CONTAINER_A',
    collectedBy: 'MEDI-04',
    date: '2026-09-11',
    time: '08:15 AM',
    status: 'VERIFIED',
    riskLevel: 'LOW',
    explanation: 'Linen wrappers and cafeteria paper napkins.',
  },
  {
    id: 'WR-2084',
    category: 'UNKNOWN',
    department: 'Operation Theatre',
    weightKg: 3.1,
    classification: 'UNKNOWN',
    confidence: 0.62,
    containerId: 'CONTAINER_B',
    collectedBy: 'Marcus Brody',
    date: '2026-09-11',
    time: '07:55 AM',
    status: 'FLAGGED',
    riskLevel: 'HIGH',
    explanation: 'Confidence < 80%. Multi-layer plastic pouch with unverified chemical label. Escalated for review.',
  },
  {
    id: 'WR-2083',
    category: 'INFECTIOUS_SOFT',
    department: 'Emergency',
    weightKg: 4.8,
    classification: 'INFECTIOUS_SOFT',
    confidence: 0.93,
    containerId: 'CONTAINER_B',
    collectedBy: 'MEDI-01',
    date: '2026-09-11',
    time: '07:30 AM',
    status: 'VERIFIED',
    riskLevel: 'HIGH',
    explanation: 'Trauma sponges and hemostatic gauze strips.',
  },
  {
    id: 'WR-2082',
    category: 'PHARMACEUTICAL',
    department: 'ICU',
    weightKg: 1.9,
    classification: 'PHARMACEUTICAL',
    confidence: 0.89,
    containerId: 'CONTAINER_D',
    collectedBy: 'MEDI-02',
    date: '2026-09-11',
    time: '07:10 AM',
    status: 'VERIFIED',
    riskLevel: 'MEDIUM',
    explanation: 'Sedation infusion syringe barrels with residual narcotic trace.',
  },
  {
    id: 'WR-2081',
    category: 'SHARPS',
    department: 'Operation Theatre',
    weightKg: 4.6,
    classification: 'SHARPS',
    confidence: 0.97,
    containerId: 'CONTAINER_C',
    collectedBy: 'MEDI-03',
    date: '2026-09-10',
    time: '18:40 PM',
    status: 'VERIFIED',
    riskLevel: 'CRITICAL',
    explanation: 'Surgical scalpel blades (#10 and #15) and wire cerclage bits.',
  },
  {
    id: 'WR-2080',
    category: 'GENERAL',
    department: 'Ward A',
    weightKg: 9.3,
    classification: 'GENERAL',
    confidence: 0.96,
    containerId: 'CONTAINER_A',
    collectedBy: 'MEDI-04',
    date: '2026-09-10',
    time: '17:25 PM',
    status: 'VERIFIED',
    riskLevel: 'LOW',
    explanation: 'Dry cardboard carton boxes and shrink-wrap.',
  },
  {
    id: 'WR-2079',
    category: 'INFECTIOUS_SOFT',
    department: 'Laboratory',
    weightKg: 5.1,
    classification: 'INFECTIOUS_SOFT',
    confidence: 0.91,
    containerId: 'CONTAINER_B',
    collectedBy: 'MEDI-01',
    date: '2026-09-10',
    time: '16:15 PM',
    status: 'VERIFIED',
    riskLevel: 'HIGH',
    explanation: 'Petri dishes and bio-agar culture swabs.',
  },
  {
    id: 'WR-2078',
    category: 'SHARPS',
    department: 'Emergency',
    weightKg: 3.5,
    classification: 'SHARPS',
    confidence: 0.94,
    containerId: 'CONTAINER_C',
    collectedBy: 'MEDI-02',
    date: '2026-09-10',
    time: '15:00 PM',
    status: 'VERIFIED',
    riskLevel: 'CRITICAL',
    explanation: 'Butterfly IV infusion needles and safety lancets.',
  },
  {
    id: 'WR-2077',
    category: 'PHARMACEUTICAL',
    department: 'Pharmacy',
    weightKg: 3.4,
    classification: 'PHARMACEUTICAL',
    confidence: 0.92,
    containerId: 'CONTAINER_D',
    collectedBy: 'MEDI-03',
    date: '2026-09-10',
    time: '14:10 PM',
    status: 'VERIFIED',
    riskLevel: 'MEDIUM',
    explanation: 'Broken glass vaccine flacons and preservative buffers.',
  },
  {
    id: 'WR-2076',
    category: 'GENERAL',
    department: 'Outpatient Department',
    weightKg: 7.6,
    classification: 'GENERAL',
    confidence: 0.97,
    containerId: 'CONTAINER_A',
    collectedBy: 'MEDI-04',
    date: '2026-09-10',
    time: '13:30 PM',
    status: 'VERIFIED',
    riskLevel: 'LOW',
    explanation: 'Patient hand towels and non-clinical clean wipes.',
  },
  {
    id: 'WR-2075',
    category: 'INFECTIOUS_SOFT',
    department: 'Ward B',
    weightKg: 6.7,
    classification: 'INFECTIOUS_SOFT',
    confidence: 0.93,
    containerId: 'CONTAINER_B',
    collectedBy: 'MEDI-01',
    date: '2026-09-10',
    time: '12:05 PM',
    status: 'VERIFIED',
    riskLevel: 'HIGH',
    explanation: 'Contaminated incontinence pads and disposable aprons.',
  },
  {
    id: 'WR-2074',
    category: 'SHARPS',
    department: 'ICU',
    weightKg: 4.1,
    classification: 'SHARPS',
    confidence: 0.95,
    containerId: 'CONTAINER_C',
    collectedBy: 'MEDI-02',
    date: '2026-09-10',
    time: '11:20 AM',
    status: 'VERIFIED',
    riskLevel: 'CRITICAL',
    explanation: 'Arterial blood gas sampling kits and heparinized needles.',
  },
  {
    id: 'WR-2073',
    category: 'UNKNOWN',
    department: 'General Medicine',
    weightKg: 2.5,
    classification: 'UNKNOWN',
    confidence: 0.54,
    containerId: 'CONTAINER_B',
    collectedBy: 'Dr. James Thorne',
    date: '2026-09-10',
    time: '10:45 AM',
    status: 'REVIEWED',
    riskLevel: 'HIGH',
    explanation: 'Initial confidence 54%. Reviewed manually by Dr. Thorne and confirmed as biological fluid absorbent.',
  },
  {
    id: 'WR-2072',
    category: 'PHARMACEUTICAL',
    department: 'Emergency',
    weightKg: 2.1,
    classification: 'PHARMACEUTICAL',
    confidence: 0.90,
    containerId: 'CONTAINER_D',
    collectedBy: 'MEDI-03',
    date: '2026-09-10',
    time: '09:10 AM',
    status: 'VERIFIED',
    riskLevel: 'MEDIUM',
    explanation: 'Epinephrine autoinjectors and opened fentanyl patches.',
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-101',
    type: 'CONTAINER NEAR FULL',
    severity: 'CRITICAL',
    message: 'Container C (Sharps) has reached 91% capacity (36.4 / 40.0 kg).',
    details: 'Decant protocol advised before incoming Emergency and ICU sharps arrive.',
    timestamp: '10:50 AM',
    read: false,
    sourceModule: 'Segregation Center',
  },
  {
    id: 'ALT-102',
    type: 'LOW SIMULATED BATTERY',
    severity: 'WARNING',
    message: 'MEDI-03 simulated battery level is critically low at 28%.',
    details: 'Unit is en route to Central Vault. Recommend auto-docking to Fast Charger 2.',
    timestamp: '10:47 AM',
    read: false,
    sourceModule: 'Mobile Units',
  },
  {
    id: 'ALT-103',
    type: 'HIGH PRIORITY COLLECTION',
    severity: 'WARNING',
    message: 'New URGENT request CR-1026 logged from Operation Theatre (Cardiac OT-3).',
    details: 'Estimated 9.0 kg infectious surgical drape packs ready for extraction.',
    timestamp: '10:44 AM',
    read: false,
    sourceModule: 'Collection Requests',
  },
  {
    id: 'ALT-104',
    type: 'AI HUMAN REVIEW REQUIRED',
    severity: 'WARNING',
    message: 'AI waste classification confidence is 62% for Operation Theatre batch WR-2084.',
    details: 'Visual ambiguity detected. Requires waste manager confirmation.',
    timestamp: '10:38 AM',
    read: false,
    sourceModule: 'AI Classification',
  },
  {
    id: 'ALT-105',
    type: 'COLLECTION DELAY',
    severity: 'INFO',
    message: 'MEDI-02 transit delayed by 4 minutes due to Corridor 3 maintenance.',
    details: 'Rerouting path calculated via Central Corridor B.',
    timestamp: '10:32 AM',
    read: true,
    sourceModule: 'Mobile Units',
  },
  {
    id: 'ALT-106',
    type: 'CONTAINER NEAR FULL',
    severity: 'WARNING',
    message: 'Container B (Infectious Soft) is filling rapidly (68% capacity reached).',
    details: 'Estimated 15 kg headroom remaining before threshold warning.',
    timestamp: '10:20 AM',
    read: true,
    sourceModule: 'Segregation Center',
  },
  {
    id: 'ALT-107',
    type: 'SYSTEM WARNING',
    severity: 'INFO',
    message: 'Automated disinfection cycle scheduled for Base Station 1 at 12:00 PM.',
    details: 'Mobile units MEDI-01 and MEDI-04 will alternate docking.',
    timestamp: '10:00 AM',
    read: true,
    sourceModule: 'System Settings',
  },
  {
    id: 'ALT-108',
    type: 'HIGH PRIORITY COLLECTION',
    severity: 'WARNING',
    message: 'Urgent collection request CR-1024 dispatched to MEDI-01.',
    details: 'Emergency department Resuscitation Bay 2.',
    timestamp: '09:45 AM',
    read: true,
    sourceModule: 'Collection Requests',
  },
  {
    id: 'ALT-109',
    type: 'AI HUMAN REVIEW REQUIRED',
    severity: 'INFO',
    message: 'Manual review completed for WR-2073 by Dr. James Thorne (Approved).',
    details: 'Biological fluid category assigned to Container B.',
    timestamp: '09:30 AM',
    read: true,
    sourceModule: 'AI Classification',
  },
  {
    id: 'ALT-110',
    type: 'SYSTEM WARNING',
    severity: 'INFO',
    message: 'Daily biological waste manifest exported for Municipal Environmental Audit.',
    details: 'SHA-256 digital signature verified: 8f9b...110a',
    timestamp: '08:00 AM',
    read: true,
    sourceModule: 'Analytics & Reports',
  },
  {
    id: 'ALT-111',
    type: 'CONTAINER FULL',
    severity: 'CRITICAL',
    message: 'Hazardous Waste Vault Compactor #2 requires filter cartridge replacement.',
    details: 'Secondary containment system is active.',
    timestamp: '07:45 AM',
    read: true,
    sourceModule: 'Segregation Center',
  },
  {
    id: 'ALT-112',
    type: 'COLLECTION DELAY',
    severity: 'INFO',
    message: 'Elevator E-4 priority medical transit override engaged.',
    details: 'Mobile unit transit times normalized.',
    timestamp: '07:15 AM',
    read: true,
    sourceModule: 'Mobile Units',
  },
  {
    id: 'ALT-113',
    type: 'SYSTEM WARNING',
    severity: 'INFO',
    message: 'MediBot Assistant knowledge base synchronized with Hospital Biohazard Protocol v4.2.',
    details: 'All classification guidelines updated.',
    timestamp: '06:00 AM',
    read: true,
    sourceModule: 'AI Assistant',
  },
  {
    id: 'ALT-114',
    type: 'HIGH PRIORITY COLLECTION',
    severity: 'WARNING',
    message: 'Early morning ICU dialysis waste collected without incident by MEDI-01.',
    details: '8.4 kg biohazard waste transferred to Container B.',
    timestamp: '09:30 AM',
    read: true,
    sourceModule: 'Collection Requests',
  },
  {
    id: 'ALT-115',
    type: 'LOW SIMULATED BATTERY',
    severity: 'INFO',
    message: 'MEDI-04 fast-charge cycle completed (100% capacity).',
    details: 'Available for immediate assignment.',
    timestamp: '10:10 AM',
    read: true,
    sourceModule: 'Mobile Units',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'LOG-3030',
    timestamp: '10:51:14 AM',
    user: 'SYSTEM (Auto-Telemetry)',
    action: 'Container Level Update',
    module: 'Segregation Center',
    description: 'Container C reached 91% capacity (36.4 kg). Warning threshold triggered.',
    status: 'ALERT',
  },
  {
    id: 'LOG-3029',
    timestamp: '10:50:02 AM',
    user: 'MEDI-01',
    action: 'Waypoint Arrival',
    module: 'Mobile Units',
    description: 'Arrived at Emergency Dept Resuscitation Bay 2 for collection CR-1024.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3028',
    timestamp: '10:48:29 AM',
    user: 'Marcus Brody',
    action: 'Audit Record Created',
    module: 'Activity Logs',
    description: 'Classification audit logged for WR-2091 with tamper-evident digital token.',
    status: 'INFO',
  },
  {
    id: 'LOG-3027',
    timestamp: '10:48:28 AM',
    user: 'Marcus Brody',
    action: 'Virtual Container Updated',
    module: 'Segregation Center',
    description: 'Virtual Container C updated: +3.8 kg sharps deposited.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3026',
    timestamp: '10:48:26 AM',
    user: 'Marcus Brody',
    action: 'Classification Approved',
    module: 'AI Classification',
    description: 'Waste Manager approved AI recommendation (SHARPS, 96% confidence).',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3025',
    timestamp: '10:48:24 AM',
    user: 'AI Engine',
    action: 'Confidence Check Passed',
    module: 'AI Classification',
    description: 'Confidence score: 96% (Threshold >= 80%). AI verified.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3024',
    timestamp: '10:48:23 AM',
    user: 'AI Engine',
    action: 'AI Classification Completed',
    module: 'AI Classification',
    description: 'Model classified sample as SHARPS with risk level CRITICAL.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3023',
    timestamp: '10:48:21 AM',
    user: 'Nurse Priya Sharma',
    action: 'Waste Image Uploaded',
    module: 'AI Classification',
    description: 'Sample high-res optical scan captured at Emergency triage station.',
    status: 'INFO',
  },
  {
    id: 'LOG-3022',
    timestamp: '10:44:12 AM',
    user: 'Marcus Brody',
    action: 'Unit Assigned',
    module: 'Collection Requests',
    description: 'MEDI-01 assigned to Collection Request CR-1024 (Emergency).',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3021',
    timestamp: '10:42:03 AM',
    user: 'Nurse Priya Sharma',
    action: 'Request Created',
    module: 'Collection Requests',
    description: 'Collection request CR-1024 created for Emergency Dept (Priority: URGENT).',
    status: 'INFO',
  },
  {
    id: 'LOG-3020',
    timestamp: '10:38:15 AM',
    user: 'AI Engine',
    action: 'Human Review Flagged',
    module: 'AI Classification',
    description: 'Confidence 62% < 80%. Batch WR-2084 flagged for mandatory waste manager review.',
    status: 'WARNING',
  },
  {
    id: 'LOG-3019',
    timestamp: '10:35:40 AM',
    user: 'David Kalu',
    action: 'Request Created',
    module: 'Collection Requests',
    description: 'Collection request CR-1025 created for Ward B (Priority: HIGH).',
    status: 'INFO',
  },
  {
    id: 'LOG-3018',
    timestamp: '10:31:12 AM',
    user: 'MEDI-02',
    action: 'Collection Started',
    module: 'Mobile Units',
    description: 'MEDI-02 dispatched from Central Bay to Ward B Corridor 3.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3017',
    timestamp: '10:25:00 AM',
    user: 'Dr. Evelyn Vance',
    action: 'System Config Modified',
    module: 'Settings',
    description: 'Safety classification threshold verified at 80% per Hospital Protocol.',
    status: 'INFO',
  },
  {
    id: 'LOG-3016',
    timestamp: '10:15:22 AM',
    user: 'Elena Rostova',
    action: 'Request Created',
    module: 'Collection Requests',
    description: 'Collection request CR-1027 created for Pharmacy (Cytotoxic vials).',
    status: 'INFO',
  },
  {
    id: 'LOG-3015',
    timestamp: '10:12:08 AM',
    user: 'MEDI-03',
    action: 'Collection Completed',
    module: 'Collection Requests',
    description: 'Collection CR-1023 completed for Outpatient Department (6.8 kg).',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3014',
    timestamp: '10:05:45 AM',
    user: 'Nurse Priya Sharma',
    action: 'Request Created',
    module: 'Collection Requests',
    description: 'Collection request CR-1031 created for Emergency triage stylets.',
    status: 'INFO',
  },
  {
    id: 'LOG-3013',
    timestamp: '09:55:18 AM',
    user: 'MEDI-02',
    action: 'Virtual Segregation',
    module: 'Segregation Center',
    description: 'Deposited 5.4 kg into Container B (Infectious Soft).',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3012',
    timestamp: '09:45:00 AM',
    user: 'Carlos Mendez, RN',
    action: 'Request Created',
    module: 'Collection Requests',
    description: 'Collection request CR-1028 created for ICU suction canisters.',
    status: 'INFO',
  },
  {
    id: 'LOG-3011',
    timestamp: '09:30:12 AM',
    user: 'MEDI-01',
    action: 'Collection Completed',
    module: 'Collection Requests',
    description: 'Collection CR-1022 completed for ICU (8.4 kg biological).',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3010',
    timestamp: '09:10:44 AM',
    user: 'MEDI-02',
    action: 'Collection Completed',
    module: 'Collection Requests',
    description: 'Collection CR-1021 completed for Laboratory microscope slides (3.9 kg).',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3009',
    timestamp: '08:52:19 AM',
    user: 'MEDI-04',
    action: 'Collection Completed',
    module: 'Collection Requests',
    description: 'Collection CR-1020 completed for General Medicine facility cleaning.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3008',
    timestamp: '08:20:05 AM',
    user: 'MEDI-03',
    action: 'Collection Completed',
    module: 'Collection Requests',
    description: 'Collection CR-1019 completed for Pharmacy expired oral antibiotics.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3007',
    timestamp: '07:55:30 AM',
    user: 'MEDI-01',
    action: 'Collection Completed',
    module: 'Collection Requests',
    description: 'Collection CR-1018 completed for Emergency Night-shift triage.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3006',
    timestamp: '07:30:14 AM',
    user: 'Dr. James Thorne',
    action: 'Audit Log Export',
    module: 'Analytics & Reports',
    description: 'Shift changeover audit verification completed and signed off.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3005',
    timestamp: '07:00:00 AM',
    user: 'SYSTEM (Boot)',
    action: 'Mobile Fleet Diagnostic',
    module: 'Mobile Units',
    description: 'Fleet initialization: 4 Mobile Units online, battery calibration passed.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3004',
    timestamp: '06:55:10 AM',
    user: 'SYSTEM (Boot)',
    action: 'Container Tare & Zero',
    module: 'Segregation Center',
    description: 'Virtual load cells synchronized: Container A, B, C, D calibrated.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3003',
    timestamp: '06:45:00 AM',
    user: 'SYSTEM (Boot)',
    action: 'AI Model Warmup',
    module: 'AI Classification',
    description: 'Vision classification engine initialized with active clinical weights.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3002',
    timestamp: '06:30:00 AM',
    user: 'Dr. Evelyn Vance',
    action: 'Role-Based Auth Audit',
    module: 'Users',
    description: 'Staff credential certificates renewed for morning roster.',
    status: 'SUCCESS',
  },
  {
    id: 'LOG-3001',
    timestamp: '06:00:00 AM',
    user: 'SYSTEM',
    action: 'System Operational Status',
    module: 'Dashboard',
    description: 'MEDI-SORT Command Center startup completed. SYSTEM STATUS: OPERATIONAL.',
    status: 'SUCCESS',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  confidenceThreshold: 0.80, // 80% default as required!
  simulationActive: true,
  simulationSpeedMs: 4000,
  alertSoundEnabled: false,
  autoSegregationAllowed: true,
  hospitalSiteName: 'St. Jude Academic Medical Center',
  theme: 'dark',
};

// Realistic clinical waste samples for instant one-click testing in AI classification
export const SAMPLE_WASTE_ITEMS = [
  {
    id: 'sample-sharps',
    title: 'Used Syringes & Needles',
    category: 'SHARPS' as const,
    expectedConfidence: 0.96,
    expectedContainer: 'CONTAINER_C' as const,
    description: 'Disposable plastic syringe barrel with 21G bevel needle and blood trace in hub.',
    risk: 'CRITICAL' as const,
    hint: 'sharp hypodermic needle syringe',
    svgColor: '#f43f5e',
    thumbnail: '💉',
  },
  {
    id: 'sample-infectious',
    title: 'Soiled Gauze & Cotton Swabs',
    category: 'INFECTIOUS_SOFT' as const,
    expectedConfidence: 0.94,
    expectedContainer: 'CONTAINER_B' as const,
    description: 'Post-operative wound dressing pads stained with bodily fluids and sterile saline.',
    risk: 'HIGH' as const,
    hint: 'infectious soft blood gauze swab dressing',
    svgColor: '#f59e0b',
    thumbnail: '🩹',
  },
  {
    id: 'sample-pharma',
    title: 'Expired Antibiotic Vials',
    category: 'PHARMACEUTICAL' as const,
    expectedConfidence: 0.91,
    expectedContainer: 'CONTAINER_D' as const,
    description: 'Glass medicine vials with discarded amoxicillin / clavulanate sodium solution.',
    risk: 'MEDIUM' as const,
    hint: 'pharmaceutical drug medicine vial antibiotic',
    svgColor: '#8b5cf6',
    thumbnail: '💊',
  },
  {
    id: 'sample-general',
    title: 'Clean Cardboard & Paper',
    category: 'GENERAL' as const,
    expectedConfidence: 0.97,
    expectedContainer: 'CONTAINER_A' as const,
    description: 'Uncontaminated medical supply shipping cartons and sterile wrapper backings.',
    risk: 'LOW' as const,
    hint: 'general uncontaminated cardboard paper clean packaging',
    svgColor: '#10b981',
    thumbnail: '📦',
  },
  {
    id: 'sample-unknown',
    title: 'Unidentified Mixed Debris',
    category: 'UNKNOWN' as const,
    expectedConfidence: 0.58, // < 80% -> HUMAN REVIEW REQUIRED!
    expectedContainer: 'CONTAINER_B' as const,
    description: 'Unmarked multi-component plastic wrap with ambiguous opaque fluid.',
    risk: 'HIGH' as const,
    hint: 'unknown ambiguous mixed debris blur',
    svgColor: '#94a3b8',
    thumbnail: '❓',
  },
];
